CREATE SCHEMA smart;

CREATE TABLE smart.points ( 
	id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY UNIQUE,
	event_name           varchar(200),
	lat                  varchar(200),
	lon                  varchar(200),
	description          varchar(200),
	image                text
 );

